openapi: 3.0.3
info:
  title: Municipal AI Platform API
  version: 1.0.0
  description: API for AI-powered municipal citizen service management
  contact:
    email: api-support@municipality.gov.in

servers:
  - url: https://api.municipality.gov.in/v1
    description: Production
  - url: https://api-staging.municipality.gov.in/v1
    description: Staging

security:
  - ApiKeyAuth: []

paths:
  /prioritize:
    post:
      summary: Score and prioritize a new ticket
      operationId: prioritizeTicket
      tags:
        - Prioritization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketInput'
      responses:
        '200':
          description: Successfully prioritized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrioritizeResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          $ref: '#/components/responses/RateLimitExceeded'
        '500':
          $ref: '#/components/responses/InternalError'
  
  /cases:
    get:
      summary: Get prioritized case list
      operationId: listCases
      tags:
        - Cases
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 500
        - name: priority
          in: query
          schema:
            type: string
            enum: [high, medium, low]
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, assigned, resolved]
      responses:
        '200':
          description: List of cases
          content:
            application/json:
              schema:
                type: object
                properties:
                  cases:
                    type: array
                    items:
                      $ref: '#/components/schemas/Case'
                  total:
                    type: integer
                  next_cursor:
                    type: string
  
  /case/{caseId}/assign:
    post:
      summary: Assign case to department/staff
      operationId: assignCase
      tags:
        - Cases
      parameters:
        - name: caseId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assignee:
                  type: string
                department:
                  type: string
                  enum: [SANITATION, ROADS, WATER, ELECTRICITY, PARKS, OTHER]
      responses:
        '200':
          description: Case assigned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
  
  /case/{caseId}/resolve:
    post:
      summary: Mark case as resolved
      operationId: resolveCase
      tags:
        - Cases
      parameters:
        - name: caseId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resolution_notes:
                  type: string
                citizen_satisfied:
                  type: boolean
      responses:
        '200':
          description: Case resolved
  
  /chat:
    post:
      summary: Citizen RAG chat (Gemini)
      operationId: citizenChat
      tags:
        - Chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  maxLength: 1000
                language:
                  type: string
                  enum: [en, mr, hi]
                  default: en
                session_id:
                  type: string
      responses:
        '200':
          description: Chat response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  
  schemas:
    TicketInput:
      type: object
      required:
        - ticket_id
        - ward
        - category
        - description
      properties:
        ticket_id:
          type: string
        citizen_id_hash:
          type: string
        ward:
          type: string
        category:
          type: string
        subcategory:
          type: string
        description:
          type: string
        photos:
          type: array
          items:
            type: string
        submitted_at:
          type: string
          format: date-time
    
    PrioritizeResponse:
      type: object
      properties:
        ticket_id:
          type: string
        priority_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        priority:
          type: string
          enum: [high, medium, low]
        will_escalate:
          type: boolean
        recommended_action:
          type: string
        features:
          type: array
          items:
            type: string
        explanation:
          type: array
          items:
            type: object
            properties:
              feature:
                type: string
              contribution:
                type: number
    
    Case:
      type: object
      properties:
        id:
          type: string
        location:
          type: string
        category:
          type: string
        score:
          type: number
        priority:
          type: string
          enum: [high, medium, low]
        status:
          type: string
          enum: [pending, assigned, resolved]
        submittedAt:
          type: string
          format: date-time
        assignee:
          type: string
        department:
          type: string
    
    ChatResponse:
      type: object
      properties:
        message:
          type: string
        sources:
          type: array
          items:
            type: string
        language:
          type: string
  
  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    
    RateLimitExceeded:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Rate limit exceeded. Retry after 60 seconds."
    
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
